version: '3.8'

services:
  brightside-ai:
    build: .
    container_name: brightside-health-ai
    ports:
      - "8501:8501"
    volumes:
      # Mount data and code for development
      - ./data:/app/data
      - ./outputs:/app/outputs
      - ./.env:/app/.env:ro
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    env_file:
      - .env
