name: brightside-health-ai
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip>=23.0
  
  # Core Scientific Computing
  - numpy>=1.24.0
  - pandas>=2.0.0
  
  # Visualization
  - matplotlib>=3.7.0
  - plotly>=5.17.0
  
  # Development Tools
  - jupyter>=1.0.0
  - pytest>=7.4.0
  - black>=23.0.0
  
  # Pip dependencies (not available in conda)
  - pip:
    - docling>=1.0.0
    - kuzu>=0.4.0
    - openai>=1.30.0
    - pydantic>=2.0.0
    - streamlit>=1.28.0
    - biothings-client>=0.3.0
    - python-dotenv>=1.0.0
    - click>=8.1.0
    - tqdm>=4.66.0
    - tiktoken>=0.5.0
    - networkx>=3.1.0